services:
  - postgres:12.2-alpine
  
variables:
    POSTGRES_DB: risc
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: abc123
    

before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
   - build
   - test
   - coverage
   - deploy
   - test-deployment

   
build:
  tags:
     - ece651
  stage: build
  script: docker build --build-arg LOCAL_USER_ID=`id -u`  --tag citest .

test:
  tags:
     - ece651
  stage: test
  script: scripts/run-tests-in-docker.sh
  artifacts:
    paths:
      - coverage

pages:
 stage: coverage
 tags:
     - ece651
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public

services:       
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: postgres
      POSTGRES_DB: risc
    restart: always
    volumes:
          - data-volume:/var/lib/postgressql/data

deploy:
  tags: 
     - ece651 
  stage: deploy
  dependencies:
     - db 
  script: ./scripts/redeploy.sh
 
test-deployment: 
  tags: 
     - ece651 
  stage: test-deployment 
  dependencies: 
     - deploy 
  script: ./scripts/test-deployment.sh
 
