version: '2'

services:
  postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: abc123
        POSTGRES_USER: postgres
        POSTGRES_DB: risc
      restart: always
      volumes:
            - data-volume:/var/lib/postgresql/data

  server:
      build: .
      command: ./gradlew run-server
      # volumes:
      #   - ./web-app:/code
      expose:
        - "1651"
        - "6666"
        - "5432"
      ports:
        - "1651:7777"
        - "6666:6666"
        - "5432:5432"
      depends_on:
        - postgres
  # ups:
  #     build: ./backend
  #     command: /code_back/runups.sh vcm-14576.vm.duke.edu vcm-14576.vm.duke.edu 5555
  #     volumes:
  #       - ./backend:/code_back
  #     depends_on:
  #       - web-init

  # nginx:
  #    image: nginx:latest
  #    ports:
  #      - "9999:9999"
  #    volumes:
  #      - ./nginx/config:/etc/nginx/conf.d
  #    depends_on:
  #      - web
volumes:
   data-volume: 
